"""Added reset_token and token_expiry to User model

Revision ID: 6019cd79ab5b
Revises: 2e153becf83c
Create Date: 2025-03-10 18:46:58.145882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6019cd79ab5b'
down_revision = '2e153becf83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
